# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 146be849b865031b6adc4d0e7fb7466977e904cdeab55ffd2426193f04948f5616ffa97fe602da40dadaf3f4114963ec3f89548daf24bd88038d7f6436789be0

test:
  secret_key_base: 843ec3ca41cf10f7177e219c881edeceeed109cc4c1a8cb7cdb42a2472dabeb75dd4b52eea825c3ef7afde727aae276677ad52c3307133a5bdaedd3a394c0134

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
